### PR TITLE
Pull latest commits from node core

### PR DESCRIPTION
**Pull request by aduh95**

### CODE REVIEW

**Review by MoLow — APPROVED** [review]
LGTM,
I'd love to know what is the procedure to cherry-pick across repos so I can do this myself

**Comment by aduh95** [comment]
I guess it would deserve to be documented somewhere. How I am doing it:

```shell
git fetch https://github.com/nodejs/node.git main
git cherry-pick -x FETCH_HEAD # instead of FETCH_HEAD, you can use a commit SHA
# ... fix the conflicts ...
# replace the URL in the files with the new git SHA
npm run test:lint:fix && npm run test:unit
# fix the failing tests, add the missing primordials, etc.
npm run test:lint:fix && npm run test:unit
git commit -S
```

**Comment by MoLow** [comment]
thanks, Il try it out on one of the next merged PRS

**Comment by MoLow** [comment]
@aduh95 added this, https://github.com/nodejs/node-core-test/wiki/How-this-repo-is-mantained

**Comment by aduh95** [comment]
https://github.com/nodejs/node-core-test/pull/34/commits/8b5a21424038788a6b6caf29eb0bb88a36897198 is not semver-minor, it should be `fix:`, not `feat:`. 

https://github.com/nodejs/node-core-test/pull/34/commits/5270582864c043eb51447cba6146e707ca002b33 should use ``fix(doc): copyedit `README.md` `` as commit title imo.

**Comment by MoLow** [comment]
Will fix later

**Comment by aduh95** [comment]
It looks like you used `-x` too many times, the `(cherry picked from commit …)` has been duplicated in both commit messages.

**Comment by MoLow** [comment]
thansk @aduh95 !

**Review by MoLow — APPROVED** [review]

**Pull request merged**
